parameters:
- name: connection
  type: string
- name: region
  type: string
  default: ap-southeast-2
- name: secretStore
  type: string
- name: secrets
  type: object

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y jq
    python -m pip install --upgrade pip==9.0.3 setuptools wheel
    pip install awscli --user
  displayName: Install AWS CLI
- task: AWSShellScript@1
  displayName: Retrieve AWS Secrets
  inputs:
    awsCredentials: ${{ parameters.connection }}
    regionName: ${{ parameters.region }}
    scriptType: inline
    inlineScript: |
      echo "Retrieving Secrets..."
      SECRETS=$(aws secretsmanager get-secret-value --secret-id ${{ parameters.secretStore }} | jq -r '.SecretString')
      for secret in $(echo "${{ join(',', parameters.secrets) }}" | sed "s/,/ /g"); do
        SECRET_KEY=$(echo $secret | cut -d':' -f1)
        ENV_NAME=$(echo $secret | cut -d':' -f2)
        ENV_VALUE=$(echo $SECRETS | jq -r ".$SECRET_KEY")
        echo -e "\t> Obtained \"$SECRET_KEY\" as \"$ENV_NAME\"."
        echo "##vso[task.setvariable variable=$ENV_NAME]$ENV_VALUE"
      done
