parameters:
- name: directory
  type: string
- name: registry
  type: string
- name: repository
  type: string
- name: tag
  type: string
    
steps:
- task: Docker@2
  displayName: Login Container Registry
  inputs:
    command: login
    containerRegistry: ${{ parameters.registry }}
- task: Docker@2
  displayName: Build and Push Container
  inputs:
    command: buildAndPush
    containerRegistry: ${{ parameters.registry }}
    repository: ${{ parameters.repository }}
    tags: ${{ parameters.tag }}
    dockerfile: ${{ format('{0}/Dockerfile', parameters.directory) }}