parameters:
- name: directory
  type: string

steps:
- task: NodeTool@0
  displayName: Install Node
  inputs:
    versionSpec: 12.x
- script: |
    yarn build
  displayName: Build Website
  workingDirectory: ${{ parameters.directory }}