parameters:
- name: directory
  type: string
- name: runTests
  type: boolean
  default: true
- name: failWithTests
  type: boolean
  default: true

steps:
- task: NodeTool@0
  displayName: Install Node
  inputs:
    versionSpec: 12.x
- script: yarn install
  displayName: Install Packages
  workingDirectory: ${{ parameters.directory }}
- script: yarn test:ci
  condition: ${{ parameters.runTests }}
  continueOnError: ${{ not(parameters.failWithTests) }}
  displayName: Test Website
  workingDirectory: ${{ parameters.directory }}
- script: yarn build
  displayName: Build Website
  workingDirectory: ${{ parameters.directory }}
- task: PublishTestResults@2
  condition: ${{ parameters.runTests }}
  displayName: Publish Website Test Results
  inputs:
    testResultsFiles: ${{ format('{0}/junit.xml', parameters.directory) }}
    mergeTestResults: true
    testRunTitle: Jest Unit Tests
    failTaskOnFailedTests: ${{ parameters.failWithTests }}