parameters:
- name: directory
  type: string
- name: runTests
  type: boolean
  default: true
- name: failWithTests
  type: boolean
  default: true
<<<<<<< HEAD
- name: buildForInfrastructure
  type: boolean
  default: false
=======
>>>>>>> master

steps:
- task: NodeTool@0
  displayName: Install Node
  inputs:
    versionSpec: 12.x
- script: yarn install
  displayName: Install Packages
  workingDirectory: ${{ parameters.directory }}
- script: yarn test:ci
  condition: ${{ parameters.runTests }}
  continueOnError: ${{ not(parameters.failWithTests) }}
  displayName: Test Website
  workingDirectory: ${{ parameters.directory }}
<<<<<<< HEAD
- ${{ if not(parameters.buildForInfrastructure) }}:
  - script: yarn build:ci
    displayName: Build Website
    workingDirectory: ${{ parameters.directory }}
- ${{ if parameters.buildForInfrastructure }}:
  - task: PowerShell@2
    displayName: Build Website
    inputs:
      targetType: filePath
      filePath: ${{ parameters.directory }}/../Infrastructure/scripts/Publish-Website.ps1
      pwsh: true
=======
- script: yarn build:ci
  displayName: Build Website
  workingDirectory: ${{ parameters.directory }}
>>>>>>> master
- task: PublishTestResults@2
  condition: ${{ parameters.runTests }}
  displayName: Publish Test Results
  inputs:
    testResultsFiles: ${{ format('{0}/junit.xml', parameters.directory) }}
    mergeTestResults: true
    testRunTitle: Jest Unit Tests
    failTaskOnFailedTests: ${{ parameters.failWithTests }}
- task: PublishCodeCoverageResults@1
  condition: ${{ parameters.runTests }}
  displayName: Publish Code Coverage Results
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: ${{ format('{0}/coverage/cobertura-coverage.xml', parameters.directory) }}
    failIfCoverageEmpty: false