name: $(revision).$(date:yyyyMMdd).$(rev:r)

trigger:
  branches:
    include:
    - master
    - development
  paths:
    include:
    - Infrastructure/pipelines/**
    exclude:
    - BackEnd/**
    - docs/**
    - Infrastructure/**
    - README.md
    - 

pool:
  vmImage: ubuntu-latest

variables:
  revision: 1
  source: $(Build.SourcesDirectory)/FrontEnd

stages:
- stage: compile
  displayName: Build & Test
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: true
    - template: ../templates/javascript-build.yaml
      parameters:
        directory: $(source)
        failWithTests: false
    - publish: $(source)/dist
      artifact: website
      displayName: Publish Website