name: $(revision).$(date:yyyyMMdd).$(rev:r)

trigger:
  branches:
    include:
    - master
    - development
  paths:
    include:
    - BackEnd/sept-registration/**
    - Infrastructure/pipelines/backend/registration/**
    - Infrastructure/pipelines/templates/java-build.yaml
    exclude:
    - FrontEnd/**
    - docs/**
    - Infrastructure/binaries/**
    - Infrastructure/binaries/**
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  revision: 1
  source: $(Build.SourcesDirectory)/BackEnd/sept-registration

stages:
- stage: compile
  displayName: Build & Test
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: true
    - template: ../../templates/java-build.yaml
      parameters:
        directory: $(source)
    # TODO: Dockerfile Publish