name: $(revision).$(date:yyyyMMdd).$(rev:r)

trigger:
  branches:
    include:
    - master
    - development
  paths:
    include:
    - BackEnd/sept-registration/**
    - Infrastructure/pipelines/backend/registration/**
    - Infrastructure/pipelines/templates/java-build.yaml
    exclude:
    - FrontEnd/**
    - docs/**
    - Infrastructure/binaries/**
    - Infrastructure/binaries/**
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  registryName: SEPT-Registry-Registration
  revision: 1
  source: $(Build.SourcesDirectory)/BackEnd/sept-registration

stages:
- stage: compile
  displayName: Build & Test
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: true
    - template: ../../templates/java-build.yaml
      parameters:
        directory: $(source)
        failWithTests: false
    - task: Docker@2
      displayName: Login Container Registry
      inputs:
        command: login
        containerRegistry: $(registryName)
    - task: Docker@2
      displayName: Build and Push Container
      inputs:
        command: buildAndPush
        containerRegistry: $(registryName)
        repository: sept/registration
        tags: $(Build.BuildNumber)
        dockerfile: $(source)/Dockerfile