name: $(revision).$(date:yyyyMMdd).$(rev:r)

parameters:
- name: port
  displayName: Application Port
  type: string
  default: 8081

trigger:
  branches:
    include:
    - master
    - development
  paths:
    include:
    - BackEnd/sept-registration/**
    - Infrastructure/pipelines/backend/registration/**
    - Infrastructure/pipelines/templates/java-build.yaml
    exclude:
    - FrontEnd/**
    - docs/**
    - Infrastructure/binaries/**
    - Infrastructure/binaries/**
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  registryName: SEPT-Registry-Registration
  revision: 1
  source: $(Build.SourcesDirectory)/BackEnd/sept-registration
  store: authentication-api

stages:
- stage: compile
  displayName: Build & Test
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: false
    - template: ../../templates/aws-retrieve-secrets.yaml
      parameters:
        connection: aws-mladenov
        secretStore: $(store)
        secrets:
        - database-endpoint:DATABASE_URL
        - database-username:DATABASE_USER
        - database-password:DATABASE_PASSWORD
        - database-driver:DATABASE_DRIVER
        - jwt:JWT_SECRET
        showResults: true
    - template: ../../templates/java-build.yaml
      parameters:
        directory: $(source)
        failWithTests: false
    #- script: |
    #    cat <<EOT >> env_file
    #   APP_PORT=${{ parameters.port }}
    #    JWT_SECRET=$ENCRYPTION_SECRET
    #    DATABASE_URL=jdbc:mysql://$DB_ENDPOINT
    #    DATABASE_USER=$DB_USER
    #    DATABASE_PASSWORD=$DB_PASSWORD
    #    DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    #    EOT
    #  displayName: Create Environments File
    #  workingDirectory: $(source)
    - template: ../../templates/container-build-push.yaml
      parameters:
        directory: $(source)
        registry: $(registryName)
        repository: sept/registration
        tag: $(Build.BuildNumber)
        arguments: '--build-arg JAR_FILE=target/*.jar'