name: $(revision).$(date:yyyyMMdd).$(rev:r)

trigger:
  branches:
    include:
    - master
    - development
  paths:
    include:
    - BackEnd/sept-profile/**
    - Infrastructure/pipelines/backend/profile/**
    - Infrastructure/pipelines/templates/java-build.yaml
    exclude:
    - FrontEnd/**
    - docs/**
    - Infrastructure/binaries/**
    - Infrastructure/binaries/**
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  registryName: SEPT-Registry-Profile
  revision: 1
  source: $(Build.SourcesDirectory)/BackEnd/sept-profile

stages:
- stage: compile
  displayName: Build & Test
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: false
    - template: ../../templates/java-build.yaml
      parameters:
        directory: $(source)
    - template: ../../templates/container-build-push.yaml
      parameters:
        directory: $(source)
        registry: $(registryName)
        repository: sept/profile
        tag: $(Build.BuildNumber)
        arguments: '--build-arg JAR_FILE=target/*.jar'
    - script: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get -yq install tree
        tree
      displayName: List All
      workingDirectory: $(source)