name: $(revision).$(date:yyyyMMdd).$(rev:r)

parameters:
- name: port
  displayName: Application Port
  type: string
  default: 8082
- name: skip
  displayName: Skip Build
  type: boolean
  default: false

trigger:
  branches:
    include:
    - master
    - development
  paths:
    include:
    - BackEnd/sept-profile/**
    - Infrastructure/pipelines/backend/profile/**
    - Infrastructure/pipelines/templates/java-build.yaml
    exclude:
    - FrontEnd/**
    - docs/**
    - Infrastructure/binaries/**
    - Infrastructure/binaries/**
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  app_port: ${{ parameters.port }}
  registryName: SEPT-Registry-Profile
  revision: 1
  source: $(Build.SourcesDirectory)/BackEnd/sept-profile

stages:
- stage: compile
  displayName: Build & Test
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: false
    - ${{ if not(parameters.skip) }}:
      - template: ../../templates/aws-retrieve-secrets.yaml
        parameters:
          connection: aws-mladenov
          secretStore: $(store)
          secrets:
          - database-endpoint:DATABASE_URL
          - database-username:DATABASE_USER
          - database-password:DATABASE_PASSWORD
          - database-driver:DATABASE_DRIVER
          - jwt:JWT_SECRET
          showResults: true
      - template: ../../templates/java-build.yaml
        parameters:
          directory: $(source)
      - template: ../../templates/container-build-push.yaml
        parameters:
          directory: $(source)
          registry: $(registryName)
          repository: sept/profile
          tag: $(Build.BuildNumber)
          arguments: '--build-arg JAR_FILE=target/*.jar'
    - publish: $(Build.SourcesDirectory)/Infrastructure
      artifact: Infrastructure
      displayName: Publish Infrastructure