ip_block                   = "10.0.0.0/16"
ip_block_prefix            = 4
ip_block_offset            = 8
eks_cluster_name           = "sept"
eks_cluster_size           = [ "t3.small", "t2.small" ]
eks_cluster_min_capacity   = 1
eks_cluster_max_capacity   = 5
eks_cluster_fault_tolerant = true
eks_cluster_administrators = [ "rmit" ]