name: $(revision).$(date:yyyyMMdd).$(rev:r)

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  revision: 1
  
stages:
- stage: compile
  displayName: Build
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: false
    - publish: $(Build.SourcesDirectory)/Infrastructure
      artifact: Infrastructure
      displayName: Publish Infrastructure
- template: ../templates/staged-deployment.yaml
  parameters:
    dependency: compile
    connection: aws-mladenov
    name: DNS
    deployment: core/dns
- template: ../templates/staged-deployment.yaml
  parameters:
    dependency: compile
    connection: aws-mladenov
    name: Orchestration
    deployment: core/orchestration