name: $(revision).$(date:yyyyMMdd).$(rev:r)

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: compile
  displayName: Build & Test
  jobs:
  - job: build
    displayName: Procedure
    steps:
    - checkout: self
      lfs: false
    - template: ../templates/deployment.yaml