server:
  port: ${APP_PORT}
jwt:
  secret: ${JWT_SECRET}
spring:
  h2:
    console:
      enabled: false
      path: /h2
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
